version: '2'

services:
  nginx:
    build: ./nginx
    image: verystar/nginx:1.9
    container_name: verystar_nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/wwwroot:/data
      - ./nginx/conf/vhost.d:/etc/nginx/conf.d

  php:
    build: ./php
    image: verystar/php:5.6.22
    container_name: verystar_php
    restart: always
    ports:
      - "9000:9000"
    links:
      - "redis"
    volumes:
      - ~/wwwroot:/data

  redis:
    build: ./redis
    image: verystar/redis:3.2
    container_name: verystar_redis
    restart: always
    ports:
      - "6379:6379"

  supervisor:
    build: ./supervisor
    image: verystar/supervisor:last
    container_name: verystar_supervisor
    restart: always
    volumes:
      - ~/wwwroot:/data
      - ./supervisor/conf/supervisor.d:/etc/supervisor