version: '2'

services:
  nginx:
    build: ./nginx
    image: fifsky/nginx:1.9
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ./nginx/conf/vhost.d:/etc/nginx/conf.d
    volumes_from:
      - php

  php:
    build: ./php
    image: fifsky/php:5.6.22
    container_name: php
    restart: always
    ports:
      - "9000:9000"
    links:
      - "redis"
      - "ssdb"
      - "gearmand"
      #- "mysql"
    volumes:
      - ./timezone:/etc/timezone
      - ./Shanghai:/etc/localtime
      - ~/wwwroot:/data
    #添加HOST
    #extra_hosts:
    #  - "db.test.cn:192.168.1.249"
    #添加额外的host绑定指向到nginx容器的IP
    #external_links:
    #  - "nginx:api.test.cn"

  redis:
    build: ./redis
    image: fifsky/redis:3.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./timezone:/etc/timezone
      - ./Shanghai:/etc/localtime

  supervisor:
    build: ./supervisor
    image: fifsky/supervisor:last
    container_name: supervisor
    restart: always
    links:
      - "gearmand"
      - "redis"
      - "ssdb"
    depends_on:
      - "php"
    volumes:
      - ./supervisor/conf/supervisor.d:/etc/supervisor
    volumes_from:
      - php

  ssdb:
    build: ./ssdb
    image: fifsky/ssdb:last
    container_name: ssdb
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./timezone:/etc/timezone
      - ./Shanghai:/etc/localtime
      - ~/wwwroot/data/ssdb:/var/lib/ssdb

  mysql:
    build: ./mysql
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "4370:4370"
    volumes:
      - ~/wwwroot/data/mysql:/var/lib/mysql
      - ./timezone:/etc/localtime
