nginx:
  build: ./nginx
  container_name: verystar_nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - ~/wwwroot:/data
    - ./nginx/conf/conf.d:/etc/nginx/conf.d

php:
  build: ./php
  container_name: verystar_php
  ports:
    - "9000:9000"
  links:
    - "redis"
  volumes:
    - ~/wwwroot:/data
    - ./php/conf/php.ini:/usr/local/etc/php/php.ini
    - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf

redis:
  build: ./redis
  container_name: verystar_redis
  ports:
    - "6379:6379"